apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    USE contador-db;
    CREATE TABLE tabla_contador (contador int NOT NULL);
    INSERT INTO tabla_contador VALUES (0);
   