apiVersion: apps/v1 
kind: Deployment  
metadata: 
  name: flask-app-deployment
spec: 
  selector:
    matchLabels:
      app: flask-app
  replicas: 1 
  template:
     metadata: 
      labels:
        app: flask-app
     spec: 
      containers:
      - name: flask-app
        image: oscarmontes/contenedores:flask-app
        env:
          # Use secret in real usage
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-manual
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
               name: flask-config
               key: MYSQL_USER
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
               name: flask-config
               key: MYSQL_HOST
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
               name: flask-config
               key: MYSQL_DATABASE
          - name: FLASK_APP
            valueFrom:
              configMapKeyRef:
               name: flask-config
               key: FLASK_APP
          - name: FLASK_ENV
            valueFrom:
              configMapKeyRef:
               name: flask-config
               key: FLASK_ENV
          - name: FLASK_RUN_HOST
            valueFrom:
              configMapKeyRef:
               name: flask-config
               key: FLASK_RUN_HOST
        ports:
        - containerPort: 5000 