# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: foo.bar.com
      paths:
      - "/"
# Secret
db:
  rootpassword: root1234
  userpassword: patodegoma
  username: keepcoding

# Configmap
dbname: contador-db
host: mysql

# Deployment
replicaCount: 1
image:
  app: "oscarmontes/contenedores:flask-app"
  db: "mysql"
  pullPolicy: IfNotPresent

# Service
service:
  type: Nodeport
  app: 5000
  port: 3306

# Autoscalado
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70


