apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "flaskapp.fullname" . }}-db
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}   
spec:
  selector:
    matchLabels:
      {{- include "flaskapp.selectorLabels" . | nindent 6 }}
      layer: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "flaskapp.selectorLabels" . | nindent 8 }}
        layer: db
    spec:
      containers:
      - image: {{ .Values.image.db }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "flaskapp.fullname" . }}-secret
              key: rootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ include "flaskapp.fullname" . }}-cm
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "flaskapp.fullname" . }}-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "flaskapp.fullname" . }}-secret
              key: userpassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: {{ include "flaskapp.fullname" . }}-mysql-pv-claim
          mountPath: /var/lib/mysql
        - name: mysql-dbscripts
          mountPath: /docker-entrypoint-initdb.d
        args: ["--max-connections", "10000"]
      volumes:
       - name: mysql-dbscripts
         configMap:
          name: {{ include "flaskapp.fullname" . }}-carga-bbdd
  volumeClaimTemplates:
  - metadata:
      name: {{ include "flaskapp.fullname" . }}-mysql-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 5Gi

